### staging ###################################################################

staging:

  hosts:
    staging:
      leihs_external_hostname: staging.leihs.zhdk.ch
      ansible_host: zhdk-leihs-staging.ruby.zhdk.ch
      zhdkaad_client_id: b26f2d22-1709-4b12-98b8-6802314f3dc1
      maintenance_page_heading: "⚠️ Leihs STAGING ⚠️"
      reverse_proxy_custom_config: |
        ProxyPass /authenticators/ms-open-id/zhdkaad http://localhost:3434/authenticators/ms-open-id/zhdkaad nocanon retry=0
        ProxyPass /zhdk-agw     http://localhost:3333/zhdk-agw	  nocanon retry=0

  vars:
    leihs_send_mails: Yes
    publish_inventory: True


### test ######################################################################

test:

  hosts:

    next:
      leihs_external_hostname: next.leihs.zhdk.ch
      ansible_host: zhdk-leihs-next.ruby.zhdk.ch
      maintenance_page_heading: "⚠️ Leihs NEXT ⚠️"
      reverse_proxy_custom_config: |
        ProxyPass /zhdk-agw     http://localhost:3333/zhdk-agw	  nocanon retry=0

    test:
      leihs_external_hostname: test.leihs.zhdk.ch
      ansible_host: zhdk-leihs-test.ruby.zhdk.ch
      maintenance_page_heading: "⚠️ Leihs TEST ⚠️"
      zhdkaad_client_id: b6d7c311-51bf-4acc-b676-ad33c41c1612
      reverse_proxy_custom_config: |
        ProxyPass /authenticators/ms-open-id/zhdkaad http://localhost:3434/authenticators/ms-open-id/zhdkaad nocanon retry=0
        ProxyPass /zhdk-agw     http://localhost:3333/zhdk-agw	  nocanon retry=0

  vars:
    leihs_send_mails: Yes
    publish_inventory: True


### dev #######################################################################


dev:

  hosts:
    jan:
    manuel:
    nimaai:
    tom:
    uvb:

  vars:
    ansible_host: '{{inventory_hostname}}-leihs.ruby.zhdk.ch'
    leihs_external_hostname: '{{inventory_hostname}}.leihs.rubydev.zhdk.ch'
    publish_inventory: True

### groupings #################################################################

restricted:
  children:
    dev:
    test:
    staging:
  vars:
    restrict_access_via_basic_auth: true
    restrict_access_via_basic_auth_passwords:
      ZHdK-Leihs-Team: "{{zhdk_leihs_team_basic_auth_password}}"
      Leihs: "{{zhdk_leihs_team_basic_auth_password}}"


zhdk:
  children:
    dev:
    staging:
    test:

non_prod:
  children:
    dev:
  hosts:
    staging:
    test:
#    test-blank:

zhdk_secrets:
  children:
    dev:
    staging:
    test:

leihs_server:
  vars:
    maintenance_page_body_paragraphs_html: ["⚠️ Leihs deploy on {{leihs_external_hostname}} is running. ⚠️"]
    ansible_user: root
    reverse_proxy_use_x_forwarded_for: true
    remote_pgbin_restore_path: /leihs/var/db-backups/latest.pgbin
    publish_inventory: False

    leihs_virtual_hosts:
    - hostname: '{{leihs_external_hostname}}'
      ip: '*'
      ssl_certificate_file: '/etc/ssl/localcerts/{{ansible_host}}.crt'
      ssl_certificate_key_file: '/etc/ssl/localcerts/{{ansible_host}}.key'
      force_redirect_to_https: yes


  children:
    dev:
    staging:
    test:
