test:
  hosts:
    test:

staging:
  hosts:
    staging:

dev:
  hosts:
    jan:
    manuel:
    nimaai:
    tom:
    uvb:

  vars:
    ansible_host: '{{inventory_hostname}}-leihs.ruby.zhdk.ch'
    leihs_external_hostname: '{{inventory_hostname}}.leihs.rubydev.zhdk.ch'
    publish_inventory: True

### groupings #################################################################

restricted:
  children:
    dev:
    test:
    staging:

zhdk:
  children:
    dev:
    staging:
    test:

zhdk_secrets:
  children:
    dev:
    staging:
    test:

leihs_server:
  children:
    dev:
    staging:
    test: