core:
  group-create-defaults:
    admin_protected: true
  group-filter-blacklist-regexes:
    - 'App_.*'
    - 'Verteilerliste.*'
    - 'Webadmin'
  group-filter-whitelist-regex: .*
  group-update-defaults:
    admin_protected: true
  source: zapi
  user-create-defaults:
    password_sign_in_enabled: false
    account_enabled: true
    admin_protected: true
  user-disable-properties:
    account_enabled: false
    address: NULL
    city: NULL
    country: NULL
    phone: NULL
    zip: NULL
  user-photo-mode: lazy
  user-update-defaults:
    account_enabled: true
    address: NULL
    admin_protected: true
    city: NULL
    country: NULL
    phone: NULL
    zip: NULL
  organization: zhdk.ch
leihs:
  base-url: 'https://{{leihs_external_hostname}}'
  token: '{{prod_v5_api_sync_token}}'
repl:
  enabled: false
  bind: localhost
  port-file: .nrepl-port
zapi:
  page-limit: 100
  token: '{{zhdk_zapi_key}}'
prtg-url: {{zhdk_prtg_url}}
