ansible_host: leihs-v4-htwchur.local
ansible_user: root

leihs_send_mails: Yes
db_backup_on_deploy: Yes
db_backup_keep_days: 10
db_backup_nigthly_enabled: Yes

ssh_keys_present:
  - "{{lookup('file', inventory_dir + '/ssh_keys/drtom')}}"
  - "{{lookup('file', inventory_dir + '/ssh_keys/mfa')}}"
  - "{{lookup('file', inventory_dir + '/ssh_keys/nimaai')}}"
