ansible_host: leihs-gw.zhdk.ch
ansible_user: root

ssh_keys_present:
  - "{{lookup('file', inventory_dir + '/ssh_keys/drtom')}}"
  - "{{lookup('file', inventory_dir + '/ssh_keys/mfa')}}"
  - "{{lookup('file', inventory_dir + '/ssh_keys/nimaai')}}"

ci_vim_mode: yes

