leihs_external_hostname: nimaai.dev.leihs.app

ansible_host: nimaai.ruby.zhdk.ch
ci_vim_mode: yes

LEIHS_DEPLOY_NEW_BORROW_APP: yes

leihs_virtual_hosts:
  - hostname: 'localhost'
    ip: 'localhost'
    logfile_infix: 'localhost'
    force_redirect_to_https: no
  - hostname: '{{leihs_external_hostname}}'
    ip: '*'
    ssl_certificate_file: '/etc/letsencrypt/live/{{leihs_external_hostname}}/fullchain.pem'
    ssl_certificate_key_file: '/etc/letsencrypt/live/{{leihs_external_hostname}}/privkey.pem'
    force_redirect_to_https: yes

# AGW
reverse_proxy_custom_config: |
  ProxyPass /zhdk-agw     http://localhost:3333/zhdk-agw	  nocanon retry=0
agw_auth_external_base_url: https://nimaai.ruby.zhdk.ch
agw_auth_port: 3333
agw_auth_private_key: '{{auth_system_master_private_key}}'
agw_auth_public_key: '{{auth_system_master_public_key}}'
agw_auth_leihs_public_key: '{{auth_system_master_public_key}}'
agw_app_id: '{{zhdk_staging_agw_app_id}}'
agw_app_secret: '{{zhdk_staging_agw_app_secret}}'
