ansible_host: 86.119.36.111
ansible_user: root

settings_file_path: '{{inventory_dir}}/settings/v51-test.yml'
shibboleth_sign_in_enabled: no
leihs_master_secret: '{{zhdk_dev_master_secret}}'

ssh_keys_present:
  - "{{lookup('file', inventory_dir + '/ssh_keys/drtom')}}"
  - "{{lookup('file', inventory_dir + '/ssh_keys/mfa')}}"
  - "{{lookup('file', inventory_dir + '/ssh_keys/nimaai')}}"
  - "{{lookup('file', inventory_dir + '/ssh_keys/zhdk_ci_executor')}}"


