leihs_external_hostname: 192.168.75.128
leihs_external_base_url: "http://{{leihs_external_hostname}}"

ansible_host: "{{leihs_external_hostname}}"
ansible_user: root

ssh_keys_present:
  - "{{lookup('file', inventory_dir + '/ssh_keys/nimaai')}}"

database_dump_restore_file_path: '{{inventory_dir}}/../legacy/tmp/db_production.pgbin'

ci_vim_mode: yes
