ansible_host: zhdk-leihs-test.ruby.zhdk.ch
ansible_user: root

# NOTE: this won't send mails to customers! the server itself
#       is configured to transparently redirect mails to a dummy mailbox!
leihs_send_mails: Yes

ssh_keys_present:
  - "{{lookup('file', inventory_dir + '/ssh_keys/drtom')}}"
  - "{{lookup('file', inventory_dir + '/ssh_keys/mfa')}}"
  - "{{lookup('file', inventory_dir + '/ssh_keys/nimaai')}}"
  - "{{lookup('file', inventory_dir + '/ssh_keys/zhdk_ci_executor')}}"

database_dump_restore_file_path: '{{inventory_dir}}/../legacy/tmp/db_production.pgbin'

zhdk_agw_info_file_path: '{{inventory_dir}}/../legacy/secrets/agw_info_test.rb'

ci_vim_mode: yes

settings:
  - name: external_base_url
    value: "https://test.leihs.zhdk.ch"
