ansible_host: zhdk-leihs-staging.ruby.zhdk.ch
ansible_user: root

db_backup_nigthly_enabled: No
db_backup_on_deploy: No
db_backup_keep_days: 1

# NOTE: this won't send mails to customers! the server itself
#       is configured to transparently redirect mails to a dummy mailbox!
leihs_send_mails: Yes

ssh_keys_present:
  - "{{lookup('file', inventory_dir + '/ssh_keys/drtom')}}"
  - "{{lookup('file', inventory_dir + '/ssh_keys/mfa')}}"
  - "{{lookup('file', inventory_dir + '/ssh_keys/nimaai')}}"
  - "{{lookup('file', inventory_dir + '/ssh_keys/zhdk_ci_executor')}}"

database_dump_restore_file_path: '{{inventory_dir}}/../legacy/tmp/db_production.pgbin'

ci_vim_mode: yes

settings_file_path: '{{inventory_dir}}/settings/zhdk-leihs-staging.yml'

# AGW

reverse_proxy_custom_config: |
  ProxyPass /zhdk-agw     http://localhost:3333/zhdk-agw	  nocanon retry=0

agw_auth_external_base_url: https://staging.leihs.zhdk.ch
agw_auth_port: 3333
agw_auth_my_private_key: '{{zhdk_staging_agw_auth_my_private_key}}'
agw_auth_my_public_key: '{{zhdk_staging_agw_auth_my_public_key}}'
agw_auth_leihs_public_key: '{{agw_auth_my_public_key}}'
agw_app_id: '{{zhdk_staging_agw_app_id}}'
agw_app_secret: '{{zhdk_staging_agw_app_secret}}'
