leihs_external_hostname: test.leihs.zhdk.ch

ansible_host: zhdk-leihs-test.ruby.zhdk.ch
ansible_user: root

# NOTE: this won't send mails to customers! the server itself
#       is configured to transparently redirect mails to a dummy mailbox!
leihs_send_mails: Yes

ssh_keys_present:
  - "{{lookup('file', inventory_dir + '/ssh_keys/drtom')}}"
  - "{{lookup('file', inventory_dir + '/ssh_keys/mfa')}}"
  - "{{lookup('file', inventory_dir + '/ssh_keys/nimaai')}}"
  - "{{lookup('file', inventory_dir + '/ssh_keys/zhdk_ci_executor')}}"

database_dump_restore_file_path: '{{inventory_dir}}/../legacy/tmp/db_production.pgbin'

zhdk_agw_info_file_path: '{{inventory_dir}}/../legacy/secrets/agw_info_test.rb'

ci_vim_mode: yes

settings_file_path: '{{inventory_dir}}/settings/zhdk-leihs-test.yml'

LEIHS_DEPLOY_NEW_BORROW_APP: yes

maintenance_page_heading: "⚠️ Leihs TEST ⚠️"
maintenance_page_body_paragraphs_html: ["development deploy is running"]
maintenance_page_status_page_url: "https://ci.zhdk.ch/"

# AGW

reverse_proxy_custom_config: |
  ProxyPass /zhdk-agw     http://localhost:3333/zhdk-agw	  nocanon retry=0

agw_auth_external_base_url: https://test.leihs.zhdk.ch
agw_auth_port: 3333
agw_auth_private_key: '{{auth_system_master_private_key}}'
agw_auth_public_key: '{{auth_system_master_public_key}}'
agw_auth_leihs_public_key: '{{auth_system_master_public_key}}'
agw_app_id: '{{zhdk_staging_agw_app_id}}'
agw_app_secret: '{{zhdk_staging_agw_app_secret}}'
