ansible_host: zhdk-leihs-prod-v5.ruby.zhdk.ch
ansible_user: root

ssh_keys_present:
  - "{{lookup('file', inventory_dir + '/ssh_keys/drtom')}}"
  - "{{lookup('file', inventory_dir + '/ssh_keys/mfa')}}"
  - "{{lookup('file', inventory_dir + '/ssh_keys/nimaai')}}"
  - "{{lookup('file', inventory_dir + '/ssh_keys/zhdk_ci_executor')}}"


database_dump_restore_file_path: '{{inventory_dir}}/../legacy/tmp/db_production.pgbin'
db_backup_on_deploy: Yes
leihs_send_mails: Yes

leihs_master_secret: '{{zhdk_prod_master_secret}}'

settings_file_path: '{{inventory_dir}}/settings/zhdk-leihs-prod.yml'

database_dump_restore_file_path: '{{inventory_dir}}/../legacy/tmp/db_production.pgbin'
db_backup_keep_days: 4
db_backup_nigthly_enabled: Yes


# AGW
 
reverse_proxy_custom_config: |
  ProxyPass /zhdk-agw     http://localhost:3333/zhdk-agw	  nocanon retry=0

agw_auth_external_base_url: https://ausleihe.zhdk.ch
agw_auth_port: 3333
agw_auth_private_key: '{{auth_system_master_private_key}}'
agw_auth_public_key: '{{auth_system_master_public_key}}'
agw_auth_leihs_public_key: '{{auth_system_master_public_key}}'
agw_app_id: '{{zhdk_prod_agw_app_id}}'
agw_app_secret: '{{zhdk_prod_agw_app_secret}}'
