ansible_host: zhdk-leihs-staging.ruby.zhdk.ch
ansible_user: root

db_backup_nigthly_enabled: No
db_backup_on_deploy: No
db_backup_keep_days: 1

ssh_keys_present:
  - "{{lookup('file', inventory_dir + '/ssh_keys/drtom')}}"
  - "{{lookup('file', inventory_dir + '/ssh_keys/mfa')}}"
  - "{{lookup('file', inventory_dir + '/ssh_keys/nimaai')}}"
  - "{{lookup('file', inventory_dir + '/ssh_keys/zhdk_ci_executor')}}"

database_dump_restore_file_path: '{{inventory_dir}}/../legacy/tmp/db_production.pgbin'

zhdk_agw_info_file_path: '{{inventory_dir}}/../legacy/secrets/agw_info_prod.rb'

ci_vim_mode: yes

settings_external_base_url: "https://staging.leihs.zhdk.ch"
