jobs:
  ###

  NIMAAI-prod:
    name: RESTORE PROD DATA and deploy to nimaai.ruby.zhdk.ch
    include: cider-ci/task-components/zhdk-dev-deploy-with-prod-data.yml
    context:
      task_defaults:
        exclusive_global_resources: { nimaai.ruby.zhdk.ch: true }
        environment_variables:
          DEPLOY_TARGET_INVENTORY: "developer-hosts --limit nimaai"

  NIMAAI-blank:
    name: Deploy to nimaai.ruby.zhdk.ch
    include: cider-ci/task-components/zhdk-dev-deploy-blank.yml
    context:
      task_defaults:
        exclusive_global_resources: { nimaai.ruby.zhdk.ch: true }
        environment_variables:
          DEPLOY_TARGET_INVENTORY: "developer-hosts --limit nimaai"

  ###

  TOM-prod:
    name: RESTORE PROD DATA and deploy to tom.ruby.zhdk.ch
    include: cider-ci/task-components/zhdk-dev-deploy-with-prod-data.yml
    context:
      task_defaults:
        exclusive_global_resources: { tom.ruby.zhdk.ch: true }
        environment_variables:
          DEPLOY_TARGET_INVENTORY: "developer-hosts --limit tom"

  TOM-blank:
    name: Deploy to tom.ruby.zhdk.ch
    include: cider-ci/task-components/zhdk-dev-deploy-blank.yml
    context:
      task_defaults:
        exclusive_global_resources: { tom.ruby.zhdk.ch: true }
        environment_variables:
          DEPLOY_TARGET_INVENTORY: "developer-hosts --limit tom"

  ###

  UVB-prod:
    name: RESTORE PROD DATA and deploy to uvb.ruby.zhdk.ch
    include: cider-ci/task-components/zhdk-dev-deploy-with-prod-data.yml
    context:
      task_defaults:
        exclusive_global_resources: { uvb.ruby.zhdk.ch: true }
        environment_variables:
          DEPLOY_TARGET_INVENTORY: "developer-hosts --limit uvb"

  UVB-blank:
    name: Deploy to uvb.ruby.zhdk.ch
    include: cider-ci/task-components/zhdk-dev-deploy-blank.yml
    context:
      task_defaults:
        exclusive_global_resources: { uvb.ruby.zhdk.ch: true }
        environment_variables:
          DEPLOY_TARGET_INVENTORY: "developer-hosts --limit uvb"
            
  ###

  JAN-prod:
    name: RESTORE PROD DATA and deploy to jan.ruby.zhdk.ch
    include: cider-ci/task-components/zhdk-dev-deploy-with-prod-data.yml
    context:
      task_defaults:
        exclusive_global_resources: { jan.ruby.zhdk.ch: true }
        environment_variables:
          DEPLOY_TARGET_INVENTORY: "developer-hosts --limit jan"

  JAN-blank:
    name: Deploy to jan.ruby.zhdk.ch
    include: cider-ci/task-components/zhdk-dev-deploy-blank.yml
    context:
      task_defaults:
        exclusive_global_resources: { jan.ruby.zhdk.ch: true }
        environment_variables:
          DEPLOY_TARGET_INVENTORY: "developer-hosts --limit jan"
            
  ###

  MANUEL-prod:
    name: RESTORE PROD DATA and deploy to manuel.ruby.zhdk.ch
    include: cider-ci/task-components/zhdk-dev-deploy-with-prod-data.yml
    context:
      task_defaults:
        exclusive_global_resources: { manuel.ruby.zhdk.ch: true }
        environment_variables:
          DEPLOY_TARGET_INVENTORY: "developer-hosts --limit manuel"

  MANUEL-blank:
    name: Deploy to manuel.ruby.zhdk.ch
    include: cider-ci/task-components/zhdk-dev-deploy-blank.yml
    context:
      task_defaults:
        exclusive_global_resources: { manuel.ruby.zhdk.ch: true }
        environment_variables:
          DEPLOY_TARGET_INVENTORY: "developer-hosts --limit manuel"
