jobs:


  ### Test #####################################################################

  test-restore-deploy:
    name: Restore prod data and deploy to test
    include: cider-ci/job-components/deploy.yml
    run_when: &RUN_ON_MASTER_AND_DO_NIGHTLY_RESET
      "deploy at 4:30 UTC":
        type: cron
        value: "30 4 * * *"
        branch_include_match: ^master$
        rerun: true
    context:
      task_defaults:
        exclusive_global_resources:
          zhdk-leihs-test.ruby.zhdk.ch: true
        environment_variables:
          DEPLOY_TARGET_INVENTORY: "hosts.yml --limit test"
        include: cider-ci/task-components/restore.yml

  test-deploy:
    name: Deploy to test.ruby.zhdk.ch
    include: cider-ci/job-components/deploy.yml
    context:
      task_defaults:
        exclusive_global_resources:
          zhdk-leihs-test.ruby.zhdk.ch: true
        environment_variables:
          DEPLOY_TARGET_INVENTORY: "hosts.yml --limit test"
    run_when:
      'on master':
        type: branch
        include_match: '^master$'
