jobs:


  ### Next #####################################################################

  next-restore-deploy:
    name: Restore prod data and deploy to next
    include: cider-ci/job-components/deploy.yml
    context:
      task_defaults:
        exclusive_global_resources:
          zhdk-leihs-next.ruby.zhdk.ch: true
        environment_variables:
          DEPLOY_TARGET_INVENTORY: "hosts.yml --limit next"
        include: cider-ci/task-components/restore.yml

  next-deploy:
    name: Deploy to next.ruby.zhdk.ch
    include: cider-ci/job-components/deploy.yml
    context:
      task_defaults:
        exclusive_global_resources:
          zhdk-leihs-next.ruby.zhdk.ch: true
        environment_variables:
          DEPLOY_TARGET_INVENTORY: "hosts.yml --limit next"


